### ISSUE TITLE
how about the requirment.txt?

### ISSUE THREAD

**Issue by chan-yuu** [HubFire/Muti-branch-DDPG-CARLA#9]
tensorflow's version

**Comment by chan-yuu** [comment]
where is the map?
Traceback (most recent call last):
  File "main.py", line 162, in <module>
    train(sess,img_agent)
  File "main.py", line 48, in train
    env = Env("./log","./data",image_agent)
  File "/home/cyun/disk3/carla_ws/Muti-branch-DDPG-CARLA/environment/carla_env.py", line 78, in __init__
    self.setup_client_and_server()
  File "/home/cyun/disk3/carla_ws/Muti-branch-DDPG-CARLA/environment/carla_env.py", line 270, in setup_client_and_server
    self.client.load_world(self.map)
RuntimeError: map not found
